name: datalens
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - arrow-cpp=21.0.0=h4e7ead5_0
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - black=25.1.0=pyha5154f8_0
  - blas=2.137=openblas
  - blas-devel=3.9.0=37_h1ea3ea9_openblas
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fastapi=0.119.1=h30ea78e_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - fastapi-core=0.119.1=pyhcf101f3_0
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.5.0=h48cff8f_0
  - greenlet=1.1.2=py310hd8f1fbe_2
  - h11=0.16.0=pyhd8ed1ab_0
  - httpcore=1.0.9=py310h06a4308_0
  - httptools=0.6.4=py310h5eee18b_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - isort=7.0.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=37_h0358290_openblas
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libidn2=2.3.2=h7f98852_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h362ad58_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.43.0=h7f98852_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lightgbm=3.3.2=py310h122e73d_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - numpy=1.22.3=py310h4ef5377_2
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.2=py310h769672d_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py310h505adc9_0
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py310h498d7c9_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - s2n=1.5.14=hdbd6064_0
  - scikit-learn=1.1.1=py310hffb9edd_0
  - scipy=1.12.0=py310heeff2f4_0
  - setuptools=80.9.0=py310h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=1.4.36=py310h5764c6d_0
  - sqlite=3.50.2=hb25bd0a_1
  - starlette=0.48.0=pyhfdc7a7d_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.16.0=py310h6acc77f_1
  - watchfiles=0.14.1=py310h3392aa1_0
  - websockets=15.0.1=py310h5eee18b_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - charset-normalizer==3.4.4
      - requests==2.32.5
      - tqdm==4.67.1
      - urllib3==2.5.0
prefix: /home/user/anaconda3/envs/datalens
